# Change these first
owner: xosan4ever # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: demis.ru
    url: https://www.demis.ru/
  - name: demis-promo.com
    url: https://demis-promo.com/
  - name: pishem-otzivi
    url: https://xn----dtbhjczpd6a7cybb.xn--p1ai/
    maxResponseTime: 7000
  - name: otzivi-tut
    url: https://xn----ctbo1audah2eb.xn--p1ai/
    maxResponseTime: 7000
  - name: sofidemarko
    url: https://sofidemarko.ru/
    

status-website:
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
